server:
  port: ${PORT:8100}
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:pabi-eureka}:${EUREKA_SERVER_PORT:8000}/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/item/**
          filters:
            - RewritePath=/api/item/(?<path>.*),/$\{path}
        - id: ${EUREKA_SERVER_NAME:pabi-eureka}
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/eureka/**